package main

import (
	"net/http"

	_ "chrisshyi.net/mini_url/docs" // docs is generated by Swag CLI, you have to import it.
	"github.com/gorilla/mux"
	httpSwagger "github.com/swaggo/http-swagger"
)

func (app *application) routes() http.Handler {

	router := mux.NewRouter()

	router.PathPrefix("/swagger").HandlerFunc(httpSwagger.WrapHandler)
	router.HandleFunc("/{shortURL}", app.redirectShortURL).Methods("GET")
	router.HandleFunc("/", app.createNewShortURL).Methods("POST")
	return router
}
